name: bun-compressor

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm install
        env:
          GITHUB_PKG_READ_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish to registry
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          GITHUB_PKG_READ_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}